### PR TITLE
Support manually in-place authentication token update

### PR DESCRIPTION
**Pull request by EAimTY**
As mentioned in #54, the lack of authentication token update mechenism may cause active `lease` and `watch` become unusable after the token expire. The solution gave in https://github.com/etcdv3/etcd-client/issues/45#issuecomment-1213260731 does theoretically solved it. However, recreating the client means every `LeaseKeeper` & `Watcher` needs to be rebuild. This makes the implementation quite complex.

Since updating token automatically is somehow difficult due to tonic's design (#45), I think updating token manually may be a better solution.

The field `token` in `AuthService` is changed to an `Arc<Mutex<Option<HeaderValue>>>` to support in-place modification and sharing between multiple services. The cost of the `Mutex` is acceptable since it only involves a clone of a small `HeaderValue` in every request.

The token update method is temporarily `Client::update_auth`. I am not sure where to put it since it may not be correspond to any service abstraction.

### CODE REVIEW

**Comment by EAimTY** [comment]
I think there are 3 ways to add the reauthentication API:

1. Add a dedicated struct `AuthHandle` as a field of `Client`. It should be able to be got by a method of `Client`, and be cloned like other fields. We can have methods like `update_token` and `remove_token` on it.
2. Add `update_token` and `remove_token` to `AuthClient`. However, this feels weird since `XxxClient` should only contains certain methods of its rpc service.
3. Keep the current design (and add `remove_token`) on `Client`. But since we need `&mut Client` everytime updating token, this may not be as flexible as the first solution.

IMO the first one is better since it could makes the reauthenticate easier without affecting other running tasks.

**Comment by davidli2010** [comment]
> I think there are 3 ways to add the reauthentication API:
> 
>     1. Add a dedicated struct `AuthHandle` as a field of `Client`. It should be able to be got by a method of `Client`, and be cloned like other fields. We can have methods like `update_token` and `remove_token` on it.
> 
>     2. Add `update_token` and `remove_token` to `AuthClient`. However, this feels weird since `XxxClient` should only contains certain methods of its rpc service.
> 
>     3. Keep the current design (and add `remove_token`) on `Client`. But since we need `&mut Client` everytime updating token, this may not be as flexible as the first solution.
> 
> 
> IMO the first one is better since it could makes the reauthenticate easier without affecting other running tasks.

I preferred the second.

**Review by davidli2010 — CHANGES_REQUESTED** [review]

**Comment by EAimTY** [comment]
> I preferred the second. Add to `AuthClient`:
> 
> ```rust
> etcd_client::auth_client().update_token(name, password);
> ```

The methods in `AuthClient` correspond one-to-one with the `service Auth` in protobuf, and all functions involve changes to the cluster configuration.

Therefore, I prefer the first approach, where the method for updating the client token is placed in a separate handler. This ensures the correspondence between XxxClient and the corresponding RPC service

**Comment by EAimTY** [comment]
> `AuthClient` is responsible for functions related to authentication

A more accurate description, in my opinion, would be that `AuthClient` is responsible for modifying and querying authentication information of the cluster. As for the token setting on the client side, I don't think it's appropriate to include them here

**Comment by davidli2010** [comment]
> > `AuthClient` is responsible for functions related to authentication
> 
> A more accurate description, in my opinion, would be that `AuthClient` is responsible for modifying and querying authentication information of the cluster. 

I don't think it's necessary to take the `AuthClient`'s responsibilities too seriously. I don't want to restrict `AuthClient` to server-side settings and create separate objects for both client-side and server-side.

**Comment by EAimTY** [comment]
I have no idea why clippy fails 😅

**Comment by davidli2010** [comment]
> I have no idea why clippy fails 😅

help: try adding this
    |
354 + impl Default for LeaderKey {
355 +     fn default() -> Self {
356 +         Self::new()
357 +     }
358 + }

**Review by davidli2010 — APPROVED** [review]

**Pull request merged**
