### PR TITLE
 Add more keys to a watch

### LINKED ISSUE #33: Adding more keys to a watch
The documentation makes it seem like I can watch additional keys on the same watcher but I don't see where or how that would work.  I don't want to create multiple watch streams so I'd prefer to just have one set of channels to and from Etcd.  Is that possible?

### PR DESCRIPTION
**Pull request by davidli2010**
close #33

### CODE REVIEW

**Comment by LizardWizzard** [comment]
> Also, I think that the watch_id param should be optional since the etcd3 server should generate an ID if we don't supply one.

IMO It makes everything much harder to deal with from the library standpoint. Currently, it is not possible to create a watch without watch_id, which means that it either should be optional which breaks the compatibility of `watch_id()` or delays the creation of a Watch until the client receives `WatchCreateResponse` which means that we either need to intercept responses in the library or need help from the application which will need to call something like `Watch::attach_watch(create_response) -> Watch`. Which will grab the id from a response and clone the channel for cancel requests

So I think the PR is good as it is :) I'll repeat myself from the issue: 
>  I think this is the best solution for flexibility/given compatibility constraints, it lets the client handle everything without changing the library. 

Though I agree that it puts more responsibility on the application. It has to track proper watch_id's by itself

**Comment by rrichardson** [comment]
Requiring a watch-id in `Watcher::watch()` is fine by me.

I would like to see the Watcher ensure that the supplied watch-id is not a duplicate of any existing (live) watch-ids. A HashSet seems simplest.

**Comment by davidli2010** [comment]
> Requiring a watch-id in `Watcher::watch()` is fine by me.
> 
> I would like to see the Watcher ensure that the supplied watch-id is not a duplicate of any existing (live) watch-ids. A HashSet seems simplest.

I have removed the required watch_id from `Watcher::watch()`, users can supply it by `WatchOptions::with_watch_id()` if they need.

In fact, if the watch_id is duplicated, etcd will return a WatchResponse with created=true, canceled=true:

```rust
WatchResponse { header: Some(ResponseHeader { cluster_id: 14841639068965178418, member_id: 10276657743932975437, revision: 657, raft_term: 6 }), watch_id: -1, created: true, canceled: true, compact_revision: 0, cancel_reason: "mvcc: duplicate watch ID provided on the WatchStream", fragment: false, events: [] }
```

So I wonder if we need to ensure the watch-id is not duplicated in `Watcher::watch()`?

**Comment by rrichardson** [comment]
> So I wonder if we need to ensure the watch-id is not duplicated in Watcher::watch()? 

 I now remember that the stated reason for the watch-id's existence is more to keep distributed clients from duplicating watches.  Doing a Set membership check on a local process doesn't do much to mitigate that. 

With that in mind, I guess the user can do their own duplication check if they want.

**Review by rrichardson — APPROVED** [review]
Apparently I can approve changes?  

They look good to me.  :)

**Review by rrichardson — APPROVED** [review]

**Pull request merged**
