### PR TITLE
chore: bump tonic to 0.7, prost to 0.10

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

After this PR gets merged, etcd-client might also bump a minor version :) Thanks for reviewing.

### CODE REVIEW

**Comment by skyzh** [comment]
Should tonic-build also be bumped to 0.7.1?

**Comment by davidli2010** [comment]
> Should tonic-build also be bumped to 0.7.1?

The lastest tonic-build is still 0.7.0

**Comment by davidli2010** [comment]
> Should tonic-build also be bumped to 0.7.1?

The lastest tonic-build is still 0.7.0

**Comment by davidli2010** [comment]
LGTM, thanks! I will release etcd-client 0.10.0

**Pull request merged**
